### ISSUE TITLE
Addition to the coding standards

### ISSUE THREAD

**Issue by oznetmaster** [nunit/dev#2]
I have noticed that a few of the source files still use qualified names in the actual code where they are either redundant, or unnecessary (e.g. no conflicts).

This is a very bad coding practice, and reduces the maintainability of the code.

ReSharper can automatically fix this, removing the qualifications, and adding using statements as necessary.

As these source files are touched for other reasons, it would be good to remove the qualifications.

Future code should really try to avoid them.

**Comment by CharliePoole** [comment]
@oznetmaster @rprouse @OsirisTerje 
As we are getting rid of this repo, I'm wondering what to do with this issue, if anything.

**Comment by rprouse** [comment]
This looks like another issue where we had high hopes and many ideas. I think it is worthwhile to carry it forward to a new repo. We could split this into two issues, one for code analysis and one for style. How does that sound? Those issues could be added to the main nunit repo or to the docs repo. My issue with docs is that we need to change the code, so it likely applies to each repo in turn.

Thoughts?

**Comment by CharliePoole** [comment]
I'd prefer to see the style-related issue in the docs repo. Docs items in the nunit repo tend not to be worked on. The code analysis issue may already be in the nunit repo separately. 

Mainly, since this issue would disappear when we remove the repo, I wanted people to put their comments that remain relevant someplace permanent.

**Comment by CharliePoole** [comment]
Alternatively, we could keep this repo and no longer use it. However, old repos seem to attract issues, which we then have to replicate elsewhere. With the small number of remaining issues, it seems we should be able to get rid of it.

**Comment by OsirisTerje** [comment]
Agree, move it over to the docs repo and then close this repo.  Normally I prefer as little documentation as possible - due to the issues with maintaining them, and code styles should be in the form of rulesets and for R#, dotsettings files, which only some explanations  and links in the docs.  My 5 cents....

**Comment by rprouse** [comment]
For no longer maintained repos collecting issues, one thing that I have seen is adding an issue template explaining that the repo is no longer maintained and directing people to the correct repo.

**Comment by CharliePoole** [comment]
We've done that in other cases but this repo had only the wiki. I deleted all the pages to avoid people getting confused by them.

**Comment by rprouse** [comment]
This issue was moved to nunit/docs#65

**Comment by rprouse** [comment]
I moved this issue over to the docs repo, so I closed this one. I will delete this repo now.
